baseURL = "https://memoja.net/"
relativeurls = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "ja-jp"
title = "投資で実現！不労所得生活"
theme = "maku"
googleAnalytics = "UA-63069513-2"

[markup.goldmark.renderer]
  unsafe = true

[params]
  sidebarLogo = "assets/img/site-logo.png"
  image = "assets/img/site-logo.png"
  facebookAppId = "525778660924912"
  Author = "まく"
  AmazonId = "maku04-22"
  CustomSearchId = "partner-pub-6317852277883092:4842999464"

